!pip install numpy

***array***

In [4]:
list = [1,2,3]
print(list)
a = np.array(list)
print(a)
print(type(a))
print(a.ndim)

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>
1


In [6]:
ar = np.array([["rahul","sohan","rohan"],["sakshi","rohit","aman"]])
print(ar)
print(ar.ndim)

[['rahul' 'sohan' 'rohan']
 ['sakshi' 'rohit' 'aman']]
2


In [9]:
arr_marks = np.array([[[[70,80,90],[67,7,89],[56,76,34],[67,49,38]]]])
print(arr_marks)
print('dimension:',arr_marks.ndim)
print('shape:',arr_marks.shape)
print('Size:',arr_marks.size)
print('data type:',arr_marks.dtype)

[[[[70 80 90]
   [67  7 89]
   [56 76 34]
   [67 49 38]]]]
dimension: 4
shape: (1, 1, 4, 3)
Size: 12
data type: int64


***Questions***

In [2]:
import numpy as np
ar = np.array([10,20,30,40,50])
print(ar)

[10 20 30 40 50]


In [5]:
ar = np.array([[1,2],[3,4]])
print(ar)
print(ar.ndim)

[[1 2]
 [3 4]]
2


In [8]:
l = [5,10,15,20]
print(l)
ar = np.array(l)
print(ar)

[5, 10, 15, 20]
[ 5 10 15 20]


***Random array***

In [12]:
ar = np.random.randint(1,10,(3,3))
print(ar)

[[7 3 5]
 [9 4 7]
 [4 2 4]]


In [14]:
import numpy as np 
arr = np.array([[10,20,30],[40,50,60]])

print("Shape =", arr.shape)
print("dimensions =", arr.ndim)
print("Total Elements =", arr.size)
print("Data type =",arr.dtype)

Shape = (2, 3)
dimensions = 2
Total Elements = 6
Data type = int64


***Zero array***

In [16]:
zero_arr = np.zeros((1,5))
print(zero_arr)

[[0. 0. 0. 0. 0.]]


***One array***


In [17]:
ar = np.ones((4,2))
print(ar)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


***Full array***

In [19]:
ar = np.full((3,3),7)
print(ar)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


***Matrix in range***

In [24]:
print(np.arange(1,11,1))

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
print(np.arange(0,21,2))

[ 0  2  4  6  8 10 12 14 16 18 20]


In [27]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


***Identity array***

In [28]:
ar = np.eye(4,4)
print(ar)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


***Empty array***

In [2]:
import numpy as np
print(np.empty(2))
print(np.empty(2))
print(np.empty(2))

[ 5.57316573e-70 -9.83345590e-57]
[ 5.57316573e-70 -9.83345590e-57]
[ 5.57316573e-70 -9.83345590e-57]


 ***Array Indexing and Slicing***

In [3]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[2])
arr[1] =100
print(arr[1])
print(arr[4])

10
50
30
100
50


In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,1])
print(arr[2,2])
print(arr[0,1])
arr[2,1] = 80
print(arr[2,1])
print(arr[1,0])

5
9
2
80
4


In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0])
print(arr[:,0])
print(arr[0:2])
print(arr[:,1:])

[1 2 3]
[1 4 7]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


***Reshaping and Flattening***

In [14]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [18]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr.reshape(1,6))

[[1 2 3 4 5 6]]


In [19]:
arr = np.array([[10,20],[30,40]])
print(arr.flatten())

[10 20 30 40]


In [21]:
arr = np.arange(1,13)
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr = np.ones((2,3))
print(arr.flatten())

[1. 1. 1. 1. 1. 1.]


***Stacking & Splitting***

In [31]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)


[1 2 3 4 5 6]


In [35]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
c =np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
a = np.array([10,20])
b = np.array([30,40])
c = np.stack((a,b))
print(c)

[[10 20]
 [30 40]]


In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

result = np.split(arr, 3)
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [39]:
arr = np.array([10,20,30,40])
result = np.split(arr,2)
print(result)

[array([10, 20]), array([30, 40])]


***Maths Operations***

In [40]:
a = np.array([1,2,3,4])
print(a+10)

[11 12 13 14]


In [41]:
b = np.array([2,4,6])
print(b*5)

[10 20 30]


In [42]:
c = np.array([10,20,30])
print(c-3)

[ 7 17 27]


In [43]:
d = np.array([20,40,60])
print(d/10)

[2. 4. 6.]


In [3]:
import numpy as np
e = np.array([1,2,3,4])
print(np.square(e))

[ 1  4  9 16]


In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.add(a,b))

[5 7 9]


In [6]:
a = np.array([10,20,30])
b = np.array([1,2,3])
print(np.subtract(a,b))

[ 9 18 27]


In [7]:
a = np.array([2,4,6])
b = np.array([1,2,3])
print(np.multiply(a,b))

[ 2  8 18]


In [8]:
a = np.array([20,40,60])
b = np.array([2,4,5])
print(np.divide(a,b))

[10. 10. 12.]


In [12]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

32


***Statistical functions***

In [13]:
a = np.array([10,20,30,40,50])
print(np.mean(a))

30.0


In [15]:
b = ([5,10,15,20,25])
print(np.median(b))

15.0


In [17]:
b = ([12,45,67,23])
print(np.max(b))

67


In [18]:
b = ([12,45,67,23])
print(np.min(b))

12


In [19]:
a = np.array([1,2,3,4,5])
print(np.sum(a))

15


In [20]:
a = np.array([2, 4, 6, 8, 10])
print(np.std(a))

2.8284271247461903


****Array Comparison****

In [21]:
a = np.array([1,2,3,4])
print(a>2)

[False False  True  True]


In [22]:
a = np.array([10, 20, 30, 40])
print(a==20)


[False  True False False]


In [23]:
a = np.array([1, 2, 3]) 
b = np.array([1, 5, 3])
print(a==b)

[ True False  True]


In [24]:
a = np.array([10,20,30])
b = np.array([5,25,30])
print(a>b)

[ True False False]


In [26]:
a = np.array([5,10,15,20,25])
print(a<18)

[ True  True  True False False]


In [33]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a==b)

[ True  True  True]


In [35]:
a = np.array([10,25,60,80,40])
print(a>50)

[False False  True  True False]
